"use client";

import dynamic from "next/dynamic";
import { useMemo, useState, type FormEvent } from "react";
import type { Place, PlaceAccess, PlaceType } from "@/lib/model";
import type { SuiteUser } from "@/lib/auth";

const PlacesMap=dynamic(()=>import("./places-map").then(module=>module.PlacesMap),{ssr:false,loading:()=><div className="map-loading"><i/><span>Preparazione della mappa aperta…</span></div>});
const typeLabels:Record<PlaceType,string>={palestra:"Palestra", "parco-attrezzato":"Parco attrezzato", "parco-libero":"Parco pubblico",garage:"Garage condiviso","centro-sportivo":"Centro sportivo",campo:"Campo o pista","casa-condivisa":"Casa messa a disposizione",altro:"Altro spazio"};
const accessLabels:Record<PlaceAccess,string>={"pubblico-gratuito":"Pubblico e gratuito","gratuito-prenotazione":"Gratuito su prenotazione","privato-condiviso":"Privato condiviso","accesso-regolato":"Accesso regolato"};

export function PlacesView({user,places,query,loginUrl,onChange,onNotice}:{user:SuiteUser|null;places:Place[];query:string;loginUrl:string;onChange:(places:Place[])=>void;onNotice:(message:string)=>void}){
  const [type,setType]=useState<PlaceType|"tutti">("tutti"); const [access,setAccess]=useState<PlaceAccess|"tutti">("tutti"); const [selectedId,setSelectedId]=useState<string|null>(places[0]?.id??null); const [adding,setAdding]=useState(false); const [coords,setCoords]=useState<{latitude:number;longitude:number}|null>(null); const [busy,setBusy]=useState(false);
  const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase("it");return places.filter(place=>(type==="tutti"||place.type===type)&&(access==="tutti"||place.access===access)&&(!needle||`${place.name} ${place.city} ${place.address} ${place.sports.join(" ")} ${place.equipment.join(" ")}`.toLocaleLowerCase("it").includes(needle)))},[places,query,type,access]);
  const selected=places.find(place=>place.id===selectedId)??filtered[0]??null;
  function startAdding(){if(!user){window.location.assign(loginUrl);return}setAdding(true);setCoords(null)}
  function locate(){navigator.geolocation?.getCurrentPosition(position=>setCoords({latitude:Number(position.coords.latitude.toFixed(6)),longitude:Number(position.coords.longitude.toFixed(6))}),()=>onNotice("Posizione non disponibile: scegli un punto sulla mappa."),{enableHighAccuracy:true,timeout:10000})}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!coords){onNotice("Scegli la posizione precisa sulla mappa.");return}setBusy(true);const body={...Object.fromEntries(new FormData(event.currentTarget).entries()),...coords};const response=await fetch("/api/places",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}).catch(()=>null);const payload=response?await response.json().catch(()=>({})) as {place?:Place;error?:string;reward?:{xp:number}}:{error:"Connessione non disponibile."};setBusy(false);if(!response?.ok||!payload.place){onNotice(payload.error||"Impossibile aggiungere il luogo.");return}onChange([payload.place,...places]);setSelectedId(payload.place.id);setAdding(false);onNotice(`Luogo aggiunto alla mappa · +${payload.reward?.xp??80} XP`)}
  async function rate(place:Place,score:number){if(!user){window.location.assign(loginUrl);return}const response=await fetch(`/api/places/${place.id}/rate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({score})}).catch(()=>null);const payload=response?await response.json().catch(()=>({})) as {place?:Place;error?:string;reward?:{xp:number}|null}:{error:"Connessione non disponibile."};if(!response?.ok||!payload.place){onNotice(payload.error||"Valutazione non riuscita.");return}onChange(places.map(item=>item.id===place.id?payload.place!:item));onNotice(payload.reward?`Valutazione registrata · +${payload.reward.xp} XP`:`Valutazione aggiornata: ${score} su 5.`)}
  return <><section className="places-hero"><div><p>ATLANTE SPORTIVO · COSTRUITO DALLA COMUNITÀ</p><h1>Ogni spazio può<br/>diventare <em>un campo.</em></h1><span>Palestre, parchi, garage, case e centri sportivi: trova dove muoverti, condividi un luogo e rendi visibile ciò che è accessibile a tutti.</span></div><button onClick={startAdding}>＋ Aggiungi un luogo</button><div className="places-signal" aria-hidden="true"><i/><i/><i/><span/></div></section>
    <section className="places-workspace"><header className="places-controls"><div><b>{filtered.length}</b><span>luoghi nella rete</span></div><label><span>TIPO</span><select value={type} onChange={event=>setType(event.target.value as PlaceType|"tutti")}><option value="tutti">Tutti gli spazi</option>{Object.entries(typeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>ACCESSO</span><select value={access} onChange={event=>setAccess(event.target.value as PlaceAccess|"tutti")}><option value="tutti">Qualsiasi accesso</option>{Object.entries(accessLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><small>Dati cartografici aperti · OpenStreetMap</small></header>
      <div className="places-layout"><div className="places-map"><PlacesMap places={filtered} selectedId={selected?.id??null} onSelect={setSelectedId} onPick={(latitude,longitude)=>setCoords({latitude,longitude})} pickMode={adding}/>{adding&&<div className="map-pick-note"><i/>Tocca la mappa per indicare l’ingresso esatto</div>}</div><aside className="places-list">{filtered.length?filtered.map(place=><PlaceCard place={place} selected={place.id===selected?.id} onSelect={()=>setSelectedId(place.id)} onRate={score=>rate(place,score)} key={place.id}/>):<div className="places-empty"><b>Nessun luogo ancora</b><span>Sii la prima persona a rendere visibile uno spazio sportivo della tua zona.</span><button onClick={startAdding}>Aggiungi alla mappa</button></div>}</aside></div>
      <section className="place-principles"><article><b>01</b><span><strong>Pubblico prima</strong><small>Parchi e spazi gratuiti sono messi in evidenza.</small></span></article><article><b>02</b><span><strong>Condiviso, non venduto</strong><small>Garage e case possono aprirsi con regole chiare.</small></span></article><article><b>03</b><span><strong>Valutato da chi lo usa</strong><small>Accessibilità, sicurezza e qualità emergono dalla rete.</small></span></article></section>
    </section>
    {adding&&<div className="place-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setAdding(false)}}><section className="place-modal" role="dialog" aria-modal="true"><header><div><span>APRI UNO SPAZIO ALLA RETE</span><h2>Aggiungi un luogo</h2></div><button onClick={()=>setAdding(false)} aria-label="Chiudi">×</button></header><form onSubmit={create}><label><span>Nome del luogo</span><input name="name" placeholder="Es. Parco delle Energie" required/></label><label><span>Tipo</span><select name="type">{Object.entries(typeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="wide"><span>Descrizione</span><textarea name="description" placeholder="Com’è lo spazio, quando è accessibile, regole utili…" required/></label><label><span>Indirizzo</span><input name="address" placeholder="Via e numero civico" required/></label><label><span>Città</span><input name="city" placeholder="Comune" required/></label><label><span>Accesso</span><select name="access">{Object.entries(accessLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>Sport possibili</span><input name="sports" placeholder="Calisthenics, corsa, yoga…"/></label><label><span>Attrezzature</span><input name="equipment" placeholder="Sbarre, campo, spogliatoi…"/></label><div className="place-checks"><label><input type="checkbox" name="indoor"/><span>Al coperto</span></label><label><input type="checkbox" name="accessible"/><span>Accessibile</span></label></div><div className={`coordinate-picker ${coords?"ready":""}`}><span><b>{coords?"Posizione impostata":"Manca la posizione"}</b><small>{coords?`${coords.latitude.toFixed(5)}, ${coords.longitude.toFixed(5)}`:"Usa la tua posizione oppure tocca la mappa."}</small></span><button type="button" onClick={locate}>Usa posizione attuale</button></div><footer><button type="button" onClick={()=>setAdding(false)}>Annulla</button><button disabled={busy}>{busy?"Pubblicazione…":"Pubblica sulla mappa →"}</button></footer></form></section></div>}
  </>;
}

function PlaceCard({place,selected,onSelect,onRate}:{place:Place;selected:boolean;onSelect:()=>void;onRate:(score:number)=>void}){return <article className={`place-card ${selected?"selected":""}`}><button className="place-card-main" onClick={onSelect}><header><i>{placeTypeMark(place.type)}</i><span><small>{typeLabels[place.type]}</small><b>{place.name}</b></span><em>{place.ratingCount?place.rating.toFixed(1):"NEW"}</em></header><p>{place.description}</p><div className="place-address">⌖ {place.address}, {place.city}</div><ul><li>{accessLabels[place.access]}</li>{place.indoor&&<li>Al coperto</li>}{place.accessible&&<li>Accessibile</li>}</ul>{place.sports.length>0&&<footer>{place.sports.slice(0,4).map(sport=><span key={sport}>{sport}</span>)}</footer>}</button><div className="place-rating"><span><b>{place.ratingCount?`${place.rating.toFixed(1)} / 5`:"Non ancora valutato"}</b><small>{place.ratingCount} {place.ratingCount===1?"valutazione":"valutazioni"}</small></span><div aria-label="Valuta questo luogo">{[1,2,3,4,5].map(score=><button onClick={()=>onRate(score)} title={`${score} su 5`} key={score}>★</button>)}</div></div></article>}
function placeTypeMark(type:PlaceType){return type==="palestra"?"GY":type.startsWith("parco")?"PK":type==="garage"?"GR":type==="centro-sportivo"?"CS":type==="campo"?"CP":type==="casa-condivisa"?"HM":"SP"}
