"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { SuiteUser } from "@/lib/auth";
import { levelProgress, levelTitle } from "@/lib/gamification";
import type { Activity, AthleteProfile, Competition, LeaderboardEntry, Lesson } from "@/lib/model";
import { sportGroups, sports } from "@/lib/sports";

const SPORT_ORIGIN="https://sport.tecnosocialismo.com";
const suiteLinks=[
  {label:"Home",href:"https://tecnosocialismo.com",mark:"T"},{label:"Iskra",href:"https://iskra.tecnosocialismo.com",mark:"I"},{label:"Rizoma",href:"https://rizoma.tecnosocialismo.com",mark:"R"},{label:"Cloud",href:"https://cloud.tecnosocialismo.com",mark:"C"},{label:"Mail",href:"https://mail.tecnosocialismo.com",mark:"M"},{label:"Video",href:"https://video.tecnosocialismo.com",mark:"V"},{label:"Social",href:"https://social.tecnosocialismo.com",mark:"S"},{label:"Sport",href:SPORT_ORIGIN,mark:"P",current:true},{label:"Messaggi",href:"https://messaggi.tecnosocialismo.com",mark:"G"},{label:"Account",href:"https://login.tecnosocialismo.com",mark:"A"},
];
type View="home"|"learn"|"teach"|"compete"|"sports"|"ranking";
type Modal="activity"|"lesson"|"competition"|null;
type ProfileView=AthleteProfile&{progress:ReturnType<typeof levelProgress>;title:string};
type Dashboard={configured:boolean;viewerId:string|null;profile:ProfileView|null;lessons:Lesson[];competitions:Competition[];activities:Activity[];leaderboard:LeaderboardEntry[]};
const emptyDashboard:Dashboard={configured:true,viewerId:null,profile:null,lessons:[],competitions:[],activities:[],leaderboard:[]};

function matchesFilter(id:string,fields:string[],selectedSport:string,query:string){
  const normalizedQuery=query.trim().toLocaleLowerCase("it");
  return(selectedSport==="tutti"||id===selectedSport)&&(!normalizedQuery||fields.some(value=>value.toLocaleLowerCase("it").includes(normalizedQuery)));
}

export function SportApp({user}:{user:SuiteUser|null}){
  const [data,setData]=useState<Dashboard>(emptyDashboard); const [loading,setLoading]=useState(true); const [view,setView]=useState<View>("home"); const [query,setQuery]=useState(""); const [sportFilter,setSportFilter]=useState("tutti"); const [groupFilter,setGroupFilter]=useState("Tutti"); const [modal,setModal]=useState<Modal>(null); const [menuOpen,setMenuOpen]=useState(false); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<string|null>(null);
  const loginUrl=`https://login.tecnosocialismo.com?returnTo=${encodeURIComponent(SPORT_ORIGIN)}`;

  useEffect(()=>{let active=true;fetch("/api/dashboard",{cache:"no-store"}).then(async(response)=>response.ok?await response.json() as Dashboard:null).catch(()=>null).then(payload=>{if(!active)return;if(payload)setData(payload);setLoading(false)});return()=>{active=false}},[]);
  useEffect(()=>{function shortcut(event:KeyboardEvent){if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();document.querySelector<HTMLInputElement>(".sport-search input")?.focus()}}window.addEventListener("keydown",shortcut);return()=>window.removeEventListener("keydown",shortcut)},[]);

  const profile=data.profile??(user?previewProfile(user):null); const progress=profile?.progress??levelProgress(0);
  const filteredLessons=useMemo(()=>data.lessons.filter(item=>matchesFilter(item.sportId,[item.sportName,item.title,item.city],sportFilter,query)),[data.lessons,query,sportFilter]);
  const filteredCompetitions=useMemo(()=>data.competitions.filter(item=>matchesFilter(item.sportId,[item.sportName,item.title,item.city],sportFilter,query)),[data.competitions,query,sportFilter]);
  const filteredSports=useMemo(()=>sports.filter(item=>(groupFilter==="Tutti"||item.group===groupFilter)&&(!query.trim()||`${item.name} ${item.group}`.toLocaleLowerCase("it").includes(query.trim().toLocaleLowerCase("it")))),[query,groupFilter]);
  function toast(message:string){setNotice(message);window.setTimeout(()=>setNotice(null),3200)}
  function requireUser(next:Modal){if(!user){window.location.assign(loginUrl);return}setModal(next)}
  function choose(next:View){setView(next);setMenuOpen(false);if(next!=="sports")setGroupFilter("Tutti")}

  async function postForm(event:FormEvent<HTMLFormElement>,endpoint:string,kind:"activity"|"lesson"|"competition"){
    event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const body=Object.fromEntries(form.entries());
    const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}).catch(()=>null);const payload=response?await response.json().catch(()=>({})) as Record<string,unknown>:{error:"Connessione non disponibile."};setBusy(false);
    if(!response?.ok){toast(typeof payload.error==="string"?payload.error:"Operazione non riuscita.");return}
    if(kind==="activity"){const raw=payload.profile as AthleteProfile;const activity=payload.activity as Activity;setData(current=>({...current,profile:{...raw,progress:levelProgress(raw.xp),title:levelTitle(raw.level)},activities:[activity,...current.activities],leaderboard:upsertRanking(current.leaderboard,raw)}));toast(`Attività registrata: +${activity.xp} XP`)}
    if(kind==="lesson"){setData(current=>({...current,lessons:[payload.lesson as Lesson,...current.lessons]}));setView("teach");toast("Lezione gratuita pubblicata.")}
    if(kind==="competition"){setData(current=>({...current,competitions:[payload.competition as Competition,...current.competitions]}));setView("compete");toast("Competizione aperta alla rete.")}
    setModal(null);
  }
  async function join(kind:"lesson"|"competition",id:string){if(!user){window.location.assign(loginUrl);return}const endpoint=kind==="lesson"?`/api/lessons/${id}/join`:`/api/competitions/${id}/join`;const response=await fetch(endpoint,{method:"POST"}).catch(()=>null);const payload=response?await response.json().catch(()=>({})) as {error?:string;lesson?:Lesson;competition?:Competition}:{error:"Connessione non disponibile."};if(!response?.ok){toast(payload.error||"Iscrizione non riuscita.");return}if(payload.lesson)setData(current=>({...current,lessons:current.lessons.map(item=>item.id===id?payload.lesson!:item)}));if(payload.competition)setData(current=>({...current,competitions:current.competitions.map(item=>item.id===id?payload.competition!:item)}));toast(kind==="lesson"?"Posto prenotato. Ci vediamo alla lezione.":"Iscrizione alla competizione confermata.")}

  return <div className="sport-shell">
    <header className="sport-topbar">
      <a className="suite-brand" href="https://tecnosocialismo.com"><span className="brand-mark"><i/><i/></span><span>TECNO<br/>SOCIALISMO</span></a>
      <a className="product-name" href={SPORT_ORIGIN}><b>SPORT</b><i>PEER TO PEER</i></a>
      <label className="sport-search"><Icon name="search"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Cerca sport, lezioni, tornei" aria-label="Cerca nel portale"/>{query?<button onClick={()=>setQuery("")} aria-label="Pulisci"><Icon name="close"/></button>:<kbd>Ctrl K</kbd>}</label>
      <button className="log-activity" onClick={()=>requireUser("activity")}><Icon name="pulse"/><span>Registra attività</span></button><SuiteMenu/>
      {user?<a className="sport-account" href="https://login.tecnosocialismo.com" title={user.email}>{initials(user.name)}</a>:<a className="sport-login" href={loginUrl}>Accedi</a>}
      <button className="sport-menu-toggle" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Apri navigazione"><Icon name="menu"/></button>
    </header>

    <aside className={`sport-sidebar ${menuOpen?"open":""}`}>
      {profile&&<button className="athlete-mini" onClick={()=>choose("home")}><LevelRing level={profile.level} progress={progress.percentage}/><span><b>{profile.name}</b><small>Livello {profile.level} · {profile.title}</small></span><Icon name="chevron"/></button>}
      <nav><p>PERCORSO</p><NavButton active={view==="home"} icon="home" label="Il mio percorso" onClick={()=>choose("home")}/><NavButton active={view==="learn"} icon="learn" label="Impara" count={data.lessons.length} onClick={()=>choose("learn")}/><NavButton active={view==="teach"} icon="teach" label="Insegna" onClick={()=>choose("teach")}/><NavButton active={view==="compete"} icon="trophy" label="Competi" count={data.competitions.length} onClick={()=>choose("compete")}/><NavButton active={view==="sports"} icon="sports" label="Tutti gli sport" onClick={()=>choose("sports")}/><NavButton active={view==="ranking"} icon="ranking" label="Classifiche" onClick={()=>choose("ranking")}/></nav>
      <section className="xp-rules"><p>COME SI SALE</p><div><i>+XP</i><span>Allenati</span></div><div><i>++</i><span>Impara</span></div><div><i>+++</i><span>Insegna gratis</span></div><div><i>★</i><span>Competi</span></div></section>
      <div className="sidebar-suite">{suiteLinks.slice(1,-1).map(link=><a href={link.href} className={link.current?"current":""} title={link.label} key={link.label}>{link.mark}</a>)}</div>
    </aside>{menuOpen&&<button className="sport-scrim" onClick={()=>setMenuOpen(false)} aria-label="Chiudi navigazione"/>}

    <main className="sport-main">
      {view==="home"&&<DashboardView user={user} profile={profile} data={data} loading={loading} configured={data.configured} onAction={requireUser} onView={choose}/>} 
      {view==="learn"&&<CatalogView title="Impara da chi è già passato di qui." kicker="LEZIONI GRATUITE · PEER TO PEER" intro="Prenota una sessione con una persona più esperta. Il sapere sportivo circola senza prezzo." action="Offri una lezione" onAction={()=>requireUser("lesson")}><FilterBar value={sportFilter} onChange={setSportFilter}/><LessonGrid items={filteredLessons} viewerId={data.viewerId} onJoin={id=>join("lesson",id)}/></CatalogView>}
      {view==="teach"&&<CatalogView title="Il tuo livello cresce quando fai crescere gli altri." kicker="INSEGNA · GUADAGNA ESPERIENZA" intro="Metti a disposizione ciò che sai. Ogni lezione resta gratuita e costruisce reputazione nella rete." action="Crea una lezione" onAction={()=>requireUser("lesson")}><div className="teaching-manifesto"><span>01</span><div><h3>Gratis, sempre.</h3><p>Nessun pagamento tra pari: la ricompensa è esperienza, reputazione e reciprocità.</p></div><span>02</span><div><h3>Un passo avanti basta.</h3><p>Non devi essere professionista: puoi aiutare chi sta iniziando il livello che hai già superato.</p></div><span>03</span><div><h3>La sicurezza prima del punteggio.</h3><p>Descrivi limiti, intensità e prerequisiti. Nessuna sfida vale un infortunio.</p></div></div><LessonGrid items={filteredLessons.filter(item=>item.hostId===data.viewerId)} viewerId={data.viewerId} onJoin={id=>join("lesson",id)} owned/></CatalogView>}
      {view==="compete"&&<CatalogView title="Tornei brevi. Campionati lunghi. Ogni sport." kicker="COMPETIZIONI · INDIVIDUALI E DI SQUADRA" intro="Organizza dal quartiere verso l’alto: regole chiare, livelli compatibili e risultati che diventano esperienza." action="Crea competizione" onAction={()=>requireUser("competition")}><FilterBar value={sportFilter} onChange={setSportFilter}/><CompetitionGrid items={filteredCompetitions} viewerId={data.viewerId} onJoin={id=>join("competition",id)}/></CatalogView>}
      {view==="sports"&&<CatalogView title="Uno spazio per ogni modo di muoversi." kicker="CATALOGO APERTO · QUALSIASI DISCIPLINA" intro="Dagli sport di squadra alle pratiche individuali. Se una disciplina manca, puoi scriverla liberamente quando crei un’attività." ><div className="group-filter"><button className={groupFilter==="Tutti"?"active":""} onClick={()=>setGroupFilter("Tutti")}>Tutti</button>{sportGroups.map(group=><button className={groupFilter===group?"active":""} onClick={()=>setGroupFilter(group)} key={group}>{group}</button>)}</div><div className="sports-grid">{filteredSports.map((sport,index)=><button key={sport.id} onClick={()=>{setSportFilter(sport.id);choose("learn")}}><span>{sport.mark}</span><small>{String(index+1).padStart(2,"0")} · {sport.group}</small><h3>{sport.name}</h3><p>{sport.mode}</p><Icon name="arrow"/></button>)}</div><div className="open-sport"><Icon name="plus"/><span><b>Non trovi il tuo sport?</b><small>Scrivilo liberamente creando una lezione, attività o competizione: il catalogo è aperto.</small></span><button onClick={()=>requireUser("activity")}>Aggiungilo</button></div></CatalogView>}
      {view==="ranking"&&<RankingView entries={data.leaderboard} viewerId={data.viewerId}/>} 
    </main>

    <aside className="sport-rail"><LevelPanel profile={profile}/><LeaderboardMini entries={data.leaderboard} viewerId={data.viewerId}/><section className="fair-play"><Icon name="shield"/><span>IL PATTO DELLA RETE</span><h3>Più forti,<br/>non più soli.</h3><p>La competizione misura il percorso. La cooperazione lo rende possibile.</p><a href="https://tecnosocialismo.com/manifesto">Principi della piattaforma <Icon name="arrow"/></a></section></aside>

    <nav className="sport-mobile-nav"><button className={view==="home"?"active":""} onClick={()=>choose("home")}><Icon name="home"/><span>Percorso</span></button><button className={view==="learn"?"active":""} onClick={()=>choose("learn")}><Icon name="learn"/><span>Impara</span></button><button className="mobile-pulse" onClick={()=>requireUser("activity")}><Icon name="plus"/></button><button className={view==="compete"?"active":""} onClick={()=>choose("compete")}><Icon name="trophy"/><span>Competi</span></button><button className={view==="ranking"?"active":""} onClick={()=>choose("ranking")}><Icon name="ranking"/><span>Classifica</span></button></nav>
    {modal&&<ModalPanel kind={modal} busy={busy} onClose={()=>setModal(null)} onSubmit={postForm}/>} {notice&&<div className="sport-toast"><i/> {notice}</div>}
  </div>
}

function DashboardView({user,profile,data,loading,configured,onAction,onView}:{user:SuiteUser|null;profile:ProfileView|null;data:Dashboard;loading:boolean;configured:boolean;onAction:(modal:Exclude<Modal,null>)=>void;onView:(view:View)=>void}){
  const progress=profile?.progress??levelProgress(0); return <>
    <section className="journey-hero"><div className="journey-copy"><p>IL MOVIMENTO È UN BENE COMUNE</p><h1>Il prossimo livello<br/>non si raggiunge <em>da soli.</em></h1><span>Impara da chi ne sa di più. Insegna ciò che hai conquistato. Competi per misurare il cammino.</span><div>{user?<><button onClick={()=>onAction("activity")}><Icon name="pulse"/>Registra attività</button><button onClick={()=>onView("learn")}>Trova una lezione <Icon name="arrow"/></button></>:<a href={`https://login.tecnosocialismo.com?returnTo=${encodeURIComponent(SPORT_ORIGIN)}`}>Inizia il percorso <Icon name="arrow"/></a>}</div></div><div className="hero-level"><div className="level-orbit"><i/><i/><i/><span><small>LVL</small><b>{profile?.level??1}</b><em>{profile?.title??"Inizio"}</em></span></div><footer><div><span>{profile?.xp??0} XP</span><b>{progress.needed-progress.current} al prossimo livello</b></div><i><b style={{width:`${progress.percentage}%`}}/></i></footer></div></section>
    {!configured&&<div className="configuration-note"><Icon name="cloud"/><span><b>Archivio da collegare</b> La piattaforma è pronta, ma la progressione online non è ancora attiva.</span></div>}
    <section className="loop-section"><header><div><span>IL CICLO</span><h2>Ogni azione apre la successiva.</h2></div><p>Il livello non misura soltanto la performance: premia costanza, conoscenza condivisa e partecipazione.</p></header><div className="loop-grid"><ActionCard index="01" icon="pulse" title="Allenati" text="Registra sessioni e costruisci continuità." meta="18–98 XP" onClick={()=>onAction("activity")}/><ActionCard index="02" icon="learn" title="Impara" text="Prenota una lezione gratuita da un pari." meta="+ esperienza" onClick={()=>onView("learn")}/><ActionCard index="03" icon="teach" title="Insegna" text="Aiuta chi sta affrontando il livello che hai superato." meta="90+ XP" onClick={()=>onAction("lesson")}/><ActionCard index="04" icon="trophy" title="Competi" text="Partecipa a tornei e campionati, da solo o in squadra." meta="110–300 XP" onClick={()=>onView("compete")}/></div></section>
    <section className="dashboard-grid"><div className="upcoming"><header><div><span>PROSSIMI APPUNTAMENTI</span><h2>La rete si muove</h2></div><button onClick={()=>onView("learn")}>Vedi tutto <Icon name="arrow"/></button></header>{loading?<Skeleton/>:data.lessons.length||data.competitions.length?<div className="upcoming-list">{[...data.lessons.slice(0,2).map(item=>({id:item.id,type:"LEZIONE",title:item.title,sport:item.sportName,date:item.startsAt,place:item.city})),...data.competitions.slice(0,2).map(item=>({id:item.id,type:item.kind.toUpperCase(),title:item.title,sport:item.sportName,date:item.startsAt,place:item.city}))].slice(0,3).map(item=><article key={item.id}><DateBadge value={item.date}/><div><small>{item.type} · {item.sport}</small><h3>{item.title}</h3><p><Icon name="pin"/>{item.place}</p></div><Icon name="chevron"/></article>)}</div>:<EmptyState icon="calendar" title="Il calendario è pronto" text="Crea la prima lezione gratuita o apri una competizione." action="Crea evento" onClick={()=>onAction("lesson")}/>}</div><div className="activity-stream"><header><span>LA TUA ATTIVITÀ</span><h2>Ultimi XP</h2></header>{profile&&data.activities.length?<div>{data.activities.slice(0,5).map(item=><article key={item.id}><i><Icon name={item.type==="victory"?"trophy":"pulse"}/></i><span><b>{item.title}</b><small>{item.sportName} · {relativeDate(item.createdAt)}</small></span><strong>+{item.xp}</strong></article>)}</div>:<EmptyState icon="pulse" title="Comincia da qui" text="Registra la tua prima attività per entrare al livello 1." action="Registra" onClick={()=>onAction("activity")}/>}</div></section>
  </>;
}

function CatalogView({title,kicker,intro,action,onAction,children}:{title:string;kicker:string;intro:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <><section className="catalog-hero"><div><p>{kicker}</p><h1>{title}</h1><span>{intro}</span></div>{action&&<button onClick={onAction}><Icon name="plus"/>{action}</button>}<div className="catalog-graph" aria-hidden="true"><i/><i/><i/><span/></div></section><section className="catalog-body">{children}</section></>}
function FilterBar({value,onChange}:{value:string;onChange:(value:string)=>void}){return <div className="filter-bar"><span>FILTRA PER SPORT</span><select value={value} onChange={event=>onChange(event.target.value)}><option value="tutti">Tutti gli sport</option>{sports.map(sport=><option value={sport.id} key={sport.id}>{sport.name}</option>)}</select><small>Il catalogo include anche discipline aggiunte liberamente dalla comunità.</small></div>}
function LessonGrid({items,viewerId,onJoin,owned=false}:{items:Lesson[];viewerId:string|null;onJoin:(id:string)=>void;owned?:boolean}){if(!items.length)return <EmptyState icon="learn" title={owned?"Non hai ancora offerto lezioni":"Nessuna lezione disponibile"} text={owned?"Condividi gratuitamente ciò che sai e costruisci esperienza.":"Apri tu il primo spazio di apprendimento tra pari."}/>;return <div className="event-grid">{items.map(item=>{const joined=viewerId?item.participantIds.includes(viewerId):false;const full=item.participantIds.length>=item.capacity;return <article className="event-card lesson-card" key={item.id}><header><span>{sportMark(item.sportId,item.sportName)}</span><div><small>LEZIONE GRATUITA</small><b>{item.sportName}</b></div><em>{item.level}</em></header><h3>{item.title}</h3><p>{item.description}</p><dl><div><dt><Icon name="calendar"/>Quando</dt><dd>{formatDate(item.startsAt)}</dd></div><div><dt><Icon name="pin"/>Dove</dt><dd>{item.city}</dd></div><div><dt><Icon name="clock"/>Durata</dt><dd>{item.durationMinutes} min</dd></div></dl><footer><span><i>{initials(item.hostName)}</i><b>{item.hostName}</b><small>offre la lezione</small></span>{item.hostId===viewerId?<button disabled>La tua lezione</button>:<button className={joined?"joined":""} disabled={joined||full} onClick={()=>onJoin(item.id)}>{joined?"Prenotata":full?"Completa":"Prenota · Gratis"}</button>}</footer><div className="capacity"><i><b style={{width:`${Math.min(100,item.participantIds.length/item.capacity*100)}%`}}/></i><span>{item.participantIds.length}/{item.capacity} posti</span></div></article>})}</div>}
function CompetitionGrid({items,viewerId,onJoin}:{items:Competition[];viewerId:string|null;onJoin:(id:string)=>void}){if(!items.length)return <EmptyState icon="trophy" title="Il tabellone è vuoto" text="Crea il primo torneo o campionato della tua comunità."/>;return <div className="event-grid">{items.map(item=>{const joined=viewerId?item.entrantIds.includes(viewerId):false;return <article className="event-card competition-card" key={item.id}><header><span>{sportMark(item.sportId,item.sportName)}</span><div><small>{item.kind.toUpperCase()} · {item.mode.toUpperCase()}</small><b>{item.sportName}</b></div><em>{item.level}</em></header><h3>{item.title}</h3><div className="bracket" aria-hidden="true"><i/><i/><i/><i/><span>VS</span></div><dl><div><dt><Icon name="calendar"/>Inizio</dt><dd>{formatDate(item.startsAt)}</dd></div><div><dt><Icon name="pin"/>Luogo</dt><dd>{item.city}</dd></div><div><dt><Icon name="people"/>Formato</dt><dd>{item.mode==="squadra"?`${item.teamSize} per squadra`:"Singolo"}</dd></div></dl><footer><span><i>{initials(item.organizerName)}</i><b>{item.organizerName}</b><small>organizza</small></span><button className={joined?"joined":""} disabled={joined} onClick={()=>onJoin(item.id)}>{joined?"Sei dentro":"Iscriviti"}</button></footer><div className="entrant-count"><Icon name="people"/>{item.entrantIds.length} {item.mode==="squadra"?"squadre":"atleti"} iscritti</div></article>})}</div>}

function RankingView({entries,viewerId}:{entries:LeaderboardEntry[];viewerId:string|null}){return <><section className="ranking-hero"><p>CLASSIFICHE · ESPERIENZA COMPLESSIVA</p><h1>La vetta conta.<br/><em>La strada di più.</em></h1><span>La classifica premia allenamento, insegnamento e competizione. Nessun livello si compra.</span></section><section className="ranking-table"><header><span>POSIZIONE</span><span>ATLETA</span><span>LEZIONI</span><span>VITTORIE</span><span>ESPERIENZA</span></header>{entries.length?entries.map((item,index)=><article className={item.id===viewerId?"you":""} key={item.id}><strong>{String(index+1).padStart(2,"0")}</strong><div><i>{initials(item.name)}</i><span><b>{item.name}</b><small>Livello {item.level}{item.id===viewerId?" · TU":""}</small></span></div><span>{item.lessonsTaught}</span><span>{item.victories}</span><em>{item.xp.toLocaleString("it-IT")} XP</em></article>):<EmptyState icon="ranking" title="La classifica comincia con te" text="Registra attività, insegna e competi per guadagnare i primi XP."/>}</section></>}

function ModalPanel({kind,busy,onClose,onSubmit}:{kind:Exclude<Modal,null>;busy:boolean;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>,endpoint:string,kind:"activity"|"lesson"|"competition")=>void}){const isActivity=kind==="activity",isLesson=kind==="lesson";return <div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="action-modal" role="dialog" aria-modal="true"><header><div><span>{isActivity?"GUADAGNA ESPERIENZA":isLesson?"CONDIVIDI COMPETENZE":"APRI LA SFIDA"}</span><h2>{isActivity?"Registra attività":isLesson?"Offri una lezione":"Crea competizione"}</h2></div><button onClick={onClose} aria-label="Chiudi"><Icon name="close"/></button></header><form onSubmit={event=>onSubmit(event,isActivity?"/api/activities":isLesson?"/api/lessons":"/api/competitions",kind)}>
  <label><span>Sport</span><input name="sport" list="sports-list" placeholder="Scrivi qualsiasi sport" required/><datalist id="sports-list">{sports.map(sport=><option value={sport.name} key={sport.id}/>)}</datalist></label>
  <label><span>{isActivity?"Descrivi l’attività":"Titolo"}</span><input name="title" placeholder={isActivity?"Es. corsa lenta sul lungomare":isLesson?"Es. Fondamentali di servizio":"Es. Coppa del quartiere"} maxLength={140} required/></label>
  {isActivity?<><label><span>Tipo</span><select name="type"><option value="training">Allenamento</option><option value="lesson">Lezione ricevuta</option><option value="teaching">Lezione insegnata gratis</option><option value="competition">Competizione disputata</option><option value="victory">Vittoria in competizione</option></select></label><label><span>Durata in minuti</span><input name="minutes" type="number" min="10" max="240" defaultValue="45" required/></label></>:<>
    {isLesson&&<label className="wide"><span>Descrizione e prerequisiti</span><textarea name="description" placeholder="Cosa farete, cosa portare e per chi è adatta…" maxLength={600} required/></label>}
    <div className="form-row"><label><span>Livello</span><select name="level"><option value="aperto">Aperto a tutti</option><option value="principiante">Principiante</option><option value="intermedio">Intermedio</option><option value="avanzato">Avanzato</option></select></label>{isLesson?<label><span>Modalità</span><select name="format"><option value="in-presenza">In presenza</option><option value="online">Online</option></select></label>:<label><span>Formula</span><select name="kind"><option value="torneo">Torneo</option><option value="campionato">Campionato</option></select></label>}</div>
    <div className="form-row">{!isLesson&&<label><span>Partecipazione</span><select name="mode"><option value="individuale">Individuale</option><option value="squadra">A squadre</option></select></label>}<label><span>Luogo</span><input name="city" placeholder={isLesson?"Città, parco o Online":"Città e impianto"} required/></label></div>
    <label><span>{isLesson?"Data e ora":"Data di inizio"}</span><input name="startsAt" type="datetime-local" required/></label>
    {isLesson?<div className="form-row"><label><span>Durata</span><input name="durationMinutes" type="number" min="20" max="240" defaultValue="60"/></label><label><span>Posti</span><input name="capacity" type="number" min="1" max="40" defaultValue="6"/></label></div>:<label><span>Persone per squadra</span><input name="teamSize" type="number" min="1" max="30" defaultValue="1"/></label>}
  </>}
  <aside><Icon name="shield"/><span><b>{isLesson?"Le lezioni restano gratuite.":"Fair play verificabile."}</b><small>{isLesson?"La ricompensa è esperienza e reputazione nella rete.":"Descrivi risultati reali: il livello è un patto di fiducia."}</small></span></aside><footer><button type="button" onClick={onClose}>Annulla</button><button disabled={busy}>{busy?"Salvataggio…":isActivity?"Ottieni XP":isLesson?"Pubblica gratis":"Apri competizione"}<Icon name="arrow"/></button></footer>
  </form></section></div>}

function LevelPanel({profile}:{profile:ProfileView|null}){const progress=profile?.progress??levelProgress(0);return <section className="level-panel"><header><span>PROGRESSIONE</span><small>STAGIONE 01</small></header><div className="level-core"><div><small>LVL</small><b>{profile?.level??1}</b><em>{profile?.title??"Inizio"}</em></div></div><h3>{profile?`${progress.needed-progress.current} XP al livello ${profile.level+1}`:"Accedi per iniziare"}</h3><i className="progress-track"><b style={{width:`${progress.percentage}%`}}/></i><footer><span><b>{profile?.streak??0}</b> giorni</span><span><b>{profile?.sessions??0}</b> attività</span><span><b>{profile?.lessonsTaught??0}</b> lezioni</span></footer></section>}
function LeaderboardMini({entries,viewerId}:{entries:LeaderboardEntry[];viewerId:string|null}){return <section className="leaderboard-mini"><header><span>CLASSIFICA APERTA</span><a href="#" onClick={event=>event.preventDefault()}>XP</a></header>{entries.length?entries.slice(0,5).map((item,index)=><div className={item.id===viewerId?"you":""} key={item.id}><small>{index+1}</small><i>{initials(item.name)}</i><span><b>{item.name}</b><em>Livello {item.level}</em></span><strong>{item.xp}</strong></div>):<p>Le prime attività costruiranno la classifica.</p>}</section>}
function ActionCard({index,icon,title,text,meta,onClick}:{index:string;icon:string;title:string;text:string;meta:string;onClick:()=>void}){return <button className="action-card" onClick={onClick}><header><small>{index}</small><i><Icon name={icon}/></i></header><h3>{title}</h3><p>{text}</p><footer><span>{meta}</span><Icon name="arrow"/></footer></button>}
function NavButton({active,icon,label,count,onClick}:{active:boolean;icon:string;label:string;count?:number;onClick:()=>void}){return <button className={active?"active":""} onClick={onClick}><Icon name={icon}/><span>{label}</span>{count!==undefined&&count>0?<small>{count}</small>:null}</button>}
function LevelRing({level,progress}:{level:number;progress:number}){return <span className="level-ring" style={{background:`conic-gradient(var(--lime) ${progress}%,rgba(255,255,255,.09) 0)`}}><i>{level}</i></span>}
function DateBadge({value}:{value:string}){const date=new Date(value);return <time dateTime={value}><b>{date.getDate()}</b><span>{date.toLocaleDateString("it-IT",{month:"short"}).toUpperCase()}</span></time>}
function EmptyState({icon,title,text,action,onClick}:{icon:string;title:string;text:string;action?:string;onClick?:()=>void}){return <div className="empty-state"><i><Icon name={icon}/></i><span><b>{title}</b><small>{text}</small></span>{action&&<button onClick={onClick}>{action}<Icon name="arrow"/></button>}</div>}
function Skeleton(){return <div className="sport-skeleton"><i/><i/><i/></div>}
function SuiteMenu(){return <details className="sport-suite-menu"><summary aria-label="Apri tutti i servizi"><span>{Array.from({length:suiteLinks.length},(_,index)=><i key={index}/>)}</span><em>Servizi</em></summary><div><p>UN ECOSISTEMA · UN ACCOUNT</p>{suiteLinks.map(link=><a className={link.current?"current":""} aria-current={link.current?"page":undefined} href={link.href} key={link.label}><i>{link.mark}</i><span>{link.label}</span><b>↗</b></a>)}</div></details>}
function previewProfile(user:SuiteUser):ProfileView{const now=new Date().toISOString();return{id:user.id,name:user.name,xp:0,level:1,streak:0,sessions:0,lessonsTaught:0,competitions:0,victories:0,sports:[],createdAt:now,updatedAt:now,progress:levelProgress(0),title:levelTitle(1)}}
function upsertRanking(entries:LeaderboardEntry[],profile:AthleteProfile){const item={id:profile.id,name:profile.name,xp:profile.xp,level:profile.level,lessonsTaught:profile.lessonsTaught,victories:profile.victories};return [...entries.filter(entry=>entry.id!==profile.id),item].sort((a,b)=>b.xp-a.xp)}
function sportMark(id:string,name:string){return sports.find(item=>item.id===id)?.mark??name.slice(0,2).toUpperCase()}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase()||"?"}
function formatDate(value:string){return new Intl.DateTimeFormat("it-IT",{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
function relativeDate(value:string){const days=Math.floor((Date.now()-new Date(value).getTime())/86_400_000);if(days<1)return"oggi";if(days===1)return"ieri";return`${days} giorni fa`}

function Icon({name}:{name:string}){const paths:Record<string,React.ReactNode>={search:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m20 20-4.8-4.8"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>,menu:<path d="M4 7h16M4 12h16M4 17h16"/>,plus:<path d="M12 5v14M5 12h14"/>,arrow:<path d="M5 12h14M14 7l5 5-5 5"/>,chevron:<path d="m9 6 6 6-6 6"/>,home:<><path d="m3 11 9-7 9 7v9H6v-9"/><path d="M10 20v-6h4v6"/></>,pulse:<path d="M3 13h4l2-7 4 13 2-6h6"/>,learn:<><path d="m3 10 9-5 9 5-9 5Z"/><path d="M7 13v4c3 2 7 2 10 0v-4M21 10v6"/></>,teach:<><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2-7 6-7s6 3 6 7M15 7h6M18 4v6"/></>,trophy:<><path d="M8 4h8v5c0 4-2 6-4 6s-4-2-4-6Z"/><path d="M8 6H4v2c0 3 2 4 4 4M16 6h4v2c0 3-2 4-4 4M12 15v4M8 21h8"/></>,sports:<><circle cx="12" cy="12" r="9"/><path d="m8 5 3 4-4 3M16 5l-3 4 4 3M7 17l5-2 5 2"/></>,ranking:<><path d="M5 20V10h4v10M10 20V4h4v16M15 20v-7h4v7"/></>,shield:<path d="M12 3 5 6v5c0 5 3 8 7 10 4-2 7-5 7-10V6Z"/>,cloud:<path d="M7 18h11a4 4 0 0 0 .4-8A7 7 0 0 0 5 9a4.5 4.5 0 0 0 2 9Z"/>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></>,pin:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,people:<><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2-7 6-7s6 3 6 7M16 5c3 0 4 2 4 4s-1 3-3 3M17 14c3 1 4 3 4 6"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>}
